### ISSUE TITLE
А вдруг в предложении между словами запятая, а не пробел?

### ISSUE THREAD

**Issue by DanaZL** [Ir4D/lesson3#1]
https://github.com/Ir4D/lesson3/blob/8826b0e734258c53ceae69c242aa8f0f16fcca77/string_challenges.py#L22

**Comment by Ir4D** [comment]
https://github.com/Ir4D/lesson3/blob/9a215a075070f4043476d479a5a06a5504d8841e/string_challenges.py#L22-L23
Добавила проверку на знаки препинания
