### ISSUE TITLE
Здесь было бы лаконичнее воспользоваться конструкцией enumerate()

### ISSUE THREAD

**Issue by DanaZL** [Ir4D/lesson3#2]
https://github.com/Ir4D/lesson3/blob/8826b0e734258c53ceae69c242aa8f0f16fcca77/for_challenges.py#L65

Попробуй почитать про нее и применить в этом задании)

**Comment by Ir4D** [comment]
https://github.com/Ir4D/lesson3/blob/1062d2da276bb324466f652e829a54fce4216d6f/for_challenges.py#L65
Применила)
