### ISSUE TITLE
Место, где очень хорошо бы встал collection.Counter

### ISSUE THREAD

**Issue by DanaZL** [Ir4D/lesson3#3]
https://github.com/Ir4D/lesson3/blob/8826b0e734258c53ceae69c242aa8f0f16fcca77/for_dict_challenges.py#L15

Попробуй применить его)

**Comment by Ir4D** [comment]
Добавила Counter:
https://github.com/Ir4D/lesson3/blob/f94112f56f6c5be73a985fccf47a4e6bca0f2294/for_dict_challenges.py#L17
