### ISSUE TITLE
Можно просто if is_male[...]:

### ISSUE THREAD

**Issue by DanaZL** [Ir4D/lesson3#4]
https://github.com/Ir4D/lesson3/blob/8826b0e734258c53ceae69c242aa8f0f16fcca77/for_dict_challenges.py#L111

Не обязательно сравнивать с True

**Comment by Ir4D** [comment]
https://github.com/Ir4D/lesson3/blob/f94112f56f6c5be73a985fccf47a4e6bca0f2294/for_dict_challenges.py#L111
https://github.com/Ir4D/lesson3/blob/f94112f56f6c5be73a985fccf47a4e6bca0f2294/for_dict_challenges.py#L113
Убрала лишние True и False
